changelog:
  categories:
    - title: 🚀 Features
      labels:
        - Feature
    - title: ♻️ Refactors
      labels:
        - Refactor
    - title: 🛠️ Fixes
      labels:
        - Fix
    - title: 🧪 Tests
      labels:
        - Test
    - title: 📚 Docs
      labels:
        - Docs
    - title: Others
      labels:
        - '*'
      exclude:
        labels:
          - Feature
          - Refactor
          - Fix
          - Test
          - Docs