name: PR Workflow

on:
  pull_request:
    types: [opened]
    branches: [main]

jobs:
  run-on-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Show Environment Variable
        env:
          MY_ENV_VAR: "42"
        run: echo "Environment variable - $MY_ENV_VAR"
      
      - name: Show Secret
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}
        run: echo "Secret variable - $MY_SECRET"